
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Role = {
  EMPLOYER: 'EMPLOYER',
  WORKER: 'WORKER'
} as const

export type Role = (typeof Role)[keyof typeof Role]


export const Category = {
  NANNY: 'NANNY',
  COOK: 'COOK',
  CLEANER: 'CLEANER',
  GARDENER: 'GARDENER',
  SECURITY: 'SECURITY',
  DRIVER: 'DRIVER',
  LAUNDRY: 'LAUNDRY'
} as const

export type Category = (typeof Category)[keyof typeof Category]


export const Availability = {
  FULL_TIME: 'FULL_TIME',
  PART_TIME: 'PART_TIME',
  LIVE_IN: 'LIVE_IN',
  LIVE_OUT: 'LIVE_OUT',
  WEEKENDS: 'WEEKENDS'
} as const

export type Availability = (typeof Availability)[keyof typeof Availability]


export const JobStatus = {
  OPEN: 'OPEN',
  CLOSED: 'CLOSED'
} as const

export type JobStatus = (typeof JobStatus)[keyof typeof JobStatus]


export const VerificationType = {
  NATIONAL_ID: 'NATIONAL_ID',
  POLICE_CLEARANCE: 'POLICE_CLEARANCE'
} as const

export type VerificationType = (typeof VerificationType)[keyof typeof VerificationType]


export const VerificationStatus = {
  VERIFIED: 'VERIFIED',
  PENDING: 'PENDING',
  REJECTED: 'REJECTED'
} as const

export type VerificationStatus = (typeof VerificationStatus)[keyof typeof VerificationStatus]


export const District = {
  GASABO: 'GASABO',
  KICUKIRO: 'KICUKIRO',
  NYARUGENGE: 'NYARUGENGE'
} as const

export type District = (typeof District)[keyof typeof District]
